name: build docker

on:
  workflow_dispatch:

jobs:
  build-standard:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Dockerfile
        uses: actions/checkout@v3
     
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/php
          file: docker/php/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
             wrhsd/wallabag:latest
          
